### ISSUE TITLE
 请问这个是给万由201P或者401P用的嘛？百度在不同的地方好像看到大佬同名的id留言

### ISSUE THREAD

**Issue by hadoken9** [mysll/unraid_i2c_tools#1]

**Comment by mysll** [comment]
是的，给万由用的

**Comment by hadoken9** [comment]
请问把插件安装后还要做什么操作吗？怎么判断有没有生效呢。

**Comment by mysll** [comment]
执行一下
modprobe i2c-dev
i2cget -y 0 0x54 0xF0
如果不报错，并且有数值就是正常的
下面一行就是输出当前的风扇转速值
如果正常，就可以把fan.sh弄成开机启动就可以了，就可以自动控制风扇的转速了

**Comment by hadoken9** [comment]
没有报错，但是反馈是0x00，风扇其实是在转的，这是不是有问题呢。

**Comment by hadoken9** [comment]
最新验证，0x00不是对应停转的，明白了。我用i2cset -y 0x54 0xF0 00，风扇是对应最低速了，i2cset -y 0x54 0xF0 150，风扇明显快了。
